### ISSUE TITLE
Výška titulků na mobilu

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/dokuwiki-plugin-newsfeed#5]
Testováno na mobilu:
- Výška proužků se zvětšuje s pořadím novinky.
- Zobrazuje se tam divný texy "newsfeed" a obrázek.

![wp_ss_20160331_0005](https://cloud.githubusercontent.com/assets/1250507/14183065/91a149fe-f76e-11e5-9072-238bbe528a8d.png)
![wp_ss_20160331_0004](https://cloud.githubusercontent.com/assets/1250507/14183066/91b6df12-f76e-11e5-81b1-096fdd9340e4.png)
![wp_ss_20160331_0003](https://cloud.githubusercontent.com/assets/1250507/14183069/91dd3be4-f76e-11e5-850e-5a61899eab82.png)
![wp_ss_20160331_0002](https://cloud.githubusercontent.com/assets/1250507/14183068/91cce564-f76e-11e5-8d52-beec90ef3dff.png)
![wp_ss_20160331_0001](https://cloud.githubusercontent.com/assets/1250507/14183070/91f4b562-f76e-11e5-870a-176be78e45a4.png)

**Comment by cevro** [comment]
Opravené, len treba prehodiť link obrázku na teste, nieje.
